version: '3'

services:
  db:
    image: postgres:11.1
  db-init:
    build:
      context: .
      dockerfile: docker/db-init/Dockerfile
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
