version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fbrain
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fbrain

  db-init:
    build:
      context: .
      dockerfile: docker/db-init/Dockerfile
    depends_on:
      - db
    networks:
      - fbrain

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fbrain

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - fbrain

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=fbrain.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    networks:
      - fbrain

  celery:
    build: ./backend
    command: celery -A fbrain worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - rabbitmq
    networks:
      - fbrain

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fbrain

volumes:
  pgdata:

networks:
  fbrain:
    driver: bridge
